---
  - name: "Add nodejs apt key"
    become: true
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: "Add nodejs 13.x ppa for apt repo"
    become: true
    apt_repository:
      repo: deb https://deb.nodesource.com/node_13.x bionic main
      update_cache: yes
        
  - name: Install ansible python3 mysql dependency
    apt:
      name: nodejs
      state: present
    register: apt_action
    retries: 100
    until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)